require:
  - rubocop/rspec/focused

AllCops:
  TargetRubyVersion: 2.3

AbcSize:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

MethodLength:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes
